# Generated by Django 6.0.3 on 2026-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="link",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
