"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ


BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    DEBUG=(bool, False),
    EMAIL_PORT=(int, 2525),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_OTP_EXPIRES_MINUTES=(int, 10),
    SERVE_MEDIA=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


def env_first(*keys, default=""):
    for key in keys:
        value = os.getenv(key)
        if value not in (None, ""):
            return value
    return default


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_first("SECRET_KEY", default="django-insecure-dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.accounts",
    "apps.links",
    "tailwind",
    "theme",
]

if DEBUG:
    INSTALLED_APPS += ["django_browser_reload"]

TAILWIND_APP_NAME = "theme"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware"]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": ["apps.links.templatetags.link_extras"],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Use DATABASE_URL when present. This supports PostgreSQL in Docker and deployment.
# If DATABASE_URL is missing, Django falls back to SQLite for quick local setup.
RUNNING_TESTS = "test" in sys.argv
default_database_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
if RUNNING_TESTS:
    # Tests default to SQLite unless TEST_DATABASE_URL is provided explicitly.
    default_database_url = f"sqlite:///{BASE_DIR / 'test_db.sqlite3'}"

DATABASES = {
    "default": env.db(
        "TEST_DATABASE_URL" if RUNNING_TESTS else "DATABASE_URL",
        default=default_database_url,
    )
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG or RUNNING_TESTS
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

WHITENOISE_USE_FINDERS = DEBUG or RUNNING_TESTS

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
SERVE_MEDIA = env.bool("SERVE_MEDIA", default=DEBUG)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# After login, redirect dashboard.
LOGIN_REDIRECT_URL = "links:dashboard"
# After logout, redirect to home page.
LOGOUT_REDIRECT_URL = "links:home"
# If a page needs login redirect to login
LOGIN_URL = "accounts:login"

# Cloudflare Turnstile
TURNSTILE_ENABLED = env_first(
    "TURNSTILE_ENABLED",
    "CLOUDFLARE_TURNSTILE_ENABLED",
    default="true",
).lower() in {"1", "true", "yes", "on"}
TURNSTILE_SITE_KEY = env_first(
    "TURNSTILE_SITE_KEY",
    "CLOUDFLARE_TURNSTILE_SITE_KEY",
    default="",
)
TURNSTILE_SECRET_KEY = env_first(
    "TURNSTILE_SECRET_KEY",
    "CLOUDFLARE_TURNSTILE_SECRET_KEY",
    default="",
)

# Mail settings
EMAIL_BACKEND = env_first(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env_first("EMAIL_HOST", "MAILTRAP_HOST", default="sandbox.smtp.mailtrap.io")
EMAIL_PORT = int(env_first("EMAIL_PORT", "MAILTRAP_PORT", default="2525"))
EMAIL_HOST_USER = env_first("EMAIL_HOST_USER", "MAILTRAP_USER", default="")
EMAIL_HOST_PASSWORD = env_first("EMAIL_HOST_PASSWORD", "MAILTRAP_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env_first(
    "DEFAULT_FROM_EMAIL",
    default="no-reply@cooplink.local",
)
SERVER_EMAIL = env_first("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

# Email OTP settings
EMAIL_OTP_EXPIRES_MINUTES = env.int("EMAIL_OTP_EXPIRES_MINUTES", default=10)
